version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
    commands:
      - pip install --upgrade awscli
      - npm install --global yarn
  pre_build:
    commands:
      - $(tsc -v)

# artifacts:
#   files:
#     - appspec.yaml
#     - taskdef.json
#   secondary-artifacts:
#     ServiceArtifact:
#       files:
#         - appspec.yaml
#         - taskdef.json
#     ServiceImageArtifact:
#       files:
#         - imageDetail.json

# cache:
#   paths:
#     - node_modules
